### ISSUE TITLE
Опечатка в документации

### ISSUE THREAD

**Issue by patgod85** [basisjs/articles#10]
На странице
https://github.com/basisjs/articles/blob/master/ru-RU/basis.dom.wrapper.md
ссылка "selection" во втором абзаце ведёт на 404:
/basisjs/articles/blob/master/ru-RU/basis.data.wrapper_selection.md

вместо неё очевидно должна быть:
/basisjs/articles/blob/master/ru-RU/basis.**dom**.wrapper_selection.md

**Comment by lahmatiy** [comment]
Спасибо! Пофиксилл 1e57a383e0df0b901d2b3c8fd034e3ecbad4507c
Но лучше делать PR ;)
